# Generated by Django 6.0.7 on 2026-07-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedWordSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
        ),
    ]
