# Generated by Django 6.0.7 on 2026-07-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_shared', '0003_uniquetestsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueTestCompositeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
    ]
