# Generated by Django 6.0.7 on 2026-07-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_shared', '0005_providerapersonsource_providerbpersonsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredSourceTestSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
