# Generated by Django 6.0.7 on 2026-07-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_shared', '0006_filteredsourcetestsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquetestsource',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
