# Generated by Django 6.0.7 on 2026-07-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_shared', '0007_uniquetestsource_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovableUniqueTestSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=20)),
            ],
        ),
    ]
