# Generated by Django 6.0.7 on 2026-08-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_shared', '0010_softdeleteuniquetestsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='NullableUniqueTestSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(max_length=20, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
