# Generated by Django 6.0.7 on 2026-08-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_shared', '0011_nullableuniquetestsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='WideCustomerSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('age', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('score', models.IntegerField(null=True)),
                ('registered_on', models.DateField(null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('region_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WideOrderLineSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price_cents', models.IntegerField()),
                ('discount_cents', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('order_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WideOrderSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=20)),
                ('total_cents', models.IntegerField()),
                ('placed_on', models.DateField(null=True)),
                ('channel', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=3)),
                ('comment', models.TextField(blank=True, default='')),
                ('customer_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WideProductSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=60)),
                ('price_cents', models.IntegerField()),
                ('weight_grams', models.IntegerField(null=True)),
                ('supplier', models.CharField(max_length=100)),
                ('discontinued', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
