# Generated by Django 6.0.7 on 2026-08-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_shared', '0012_widecustomersource_wideorderlinesource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardDeleteCountTestSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
            ],
        ),
    ]
