# Generated by Django 6.0.7 on 2026-08-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_shared', '0013_harddeletecounttestsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntrySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemberSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RosterMembershipSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_id', models.IntegerField()),
                ('member_id', models.IntegerField()),
                ('role', models.CharField(default='member', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RosterSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
