# Generated by Django 6.0.7 on 2026-08-14 21:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_shared', '0014_auditentrysource_membersource_rostermembershipsource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberUuid7PolyfillSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RosterMembershipUuid7PolyfillSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roster_id', models.UUIDField()),
                ('member_id', models.UUIDField()),
                ('role', models.CharField(default='member', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RosterUuid7PolyfillSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
