# Generated by Django 6.0.7 on 2026-08-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_shared', '0016_widecustomeru7source_wideorderlineu7source_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='widecustomersource',
            index=models.Index(fields=['last_name'], name='wcs_last_name_idx'),
        ),
        migrations.AddIndex(
            model_name='widecustomersource',
            index=models.Index(fields=['city'], name='wcs_city_idx'),
        ),
        migrations.AddIndex(
            model_name='widecustomersource',
            index=models.Index(fields=['status'], name='wcs_status_idx'),
        ),
        migrations.AddIndex(
            model_name='widecustomersource',
            index=models.Index(fields=['score'], name='wcs_score_idx'),
        ),
        migrations.AddIndex(
            model_name='widecustomersource',
            index=models.Index(fields=['age'], name='wcs_age_idx'),
        ),
        migrations.AddIndex(
            model_name='widecustomeru7source',
            index=models.Index(fields=['last_name'], name='wcs7_last_name_idx'),
        ),
        migrations.AddIndex(
            model_name='widecustomeru7source',
            index=models.Index(fields=['city'], name='wcs7_city_idx'),
        ),
        migrations.AddIndex(
            model_name='widecustomeru7source',
            index=models.Index(fields=['status'], name='wcs7_status_idx'),
        ),
        migrations.AddIndex(
            model_name='widecustomeru7source',
            index=models.Index(fields=['score'], name='wcs7_score_idx'),
        ),
        migrations.AddIndex(
            model_name='widecustomeru7source',
            index=models.Index(fields=['age'], name='wcs7_age_idx'),
        ),
        migrations.AddIndex(
            model_name='wideorderlinesource',
            index=models.Index(fields=['order_id'], name='wols_order_id_idx'),
        ),
        migrations.AddIndex(
            model_name='wideorderlinesource',
            index=models.Index(fields=['product_id'], name='wols_product_id_idx'),
        ),
        migrations.AddIndex(
            model_name='wideorderlineu7source',
            index=models.Index(fields=['order_id'], name='wols7_order_id_idx'),
        ),
        migrations.AddIndex(
            model_name='wideorderlineu7source',
            index=models.Index(fields=['product_id'], name='wols7_product_id_idx'),
        ),
        migrations.AddIndex(
            model_name='wideordersource',
            index=models.Index(fields=['status'], name='wos_status_idx'),
        ),
        migrations.AddIndex(
            model_name='wideordersource',
            index=models.Index(fields=['channel'], name='wos_channel_idx'),
        ),
        migrations.AddIndex(
            model_name='wideordersource',
            index=models.Index(fields=['customer_id'], name='wos_customer_id_idx'),
        ),
        migrations.AddIndex(
            model_name='wideorderu7source',
            index=models.Index(fields=['status'], name='wos7_status_idx'),
        ),
        migrations.AddIndex(
            model_name='wideorderu7source',
            index=models.Index(fields=['channel'], name='wos7_channel_idx'),
        ),
        migrations.AddIndex(
            model_name='wideorderu7source',
            index=models.Index(fields=['customer_id'], name='wos7_customer_id_idx'),
        ),
        migrations.AddIndex(
            model_name='wideproductsource',
            index=models.Index(fields=['category'], name='wps_category_idx'),
        ),
        migrations.AddIndex(
            model_name='wideproductsource',
            index=models.Index(fields=['sku'], name='wps_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='wideproductu7source',
            index=models.Index(fields=['category'], name='wps7_category_idx'),
        ),
        migrations.AddIndex(
            model_name='wideproductu7source',
            index=models.Index(fields=['sku'], name='wps7_sku_idx'),
        ),
    ]
