# Generated by Django 6.0.7 on 2026-08-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_shared', '0017_widecustomersource_wcs_last_name_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rostermembershipsource',
            index=models.Index(fields=['roster_id'], name='rms_roster_id_idx'),
        ),
        migrations.AddIndex(
            model_name='rostermembershipsource',
            index=models.Index(fields=['member_id'], name='rms_member_id_idx'),
        ),
        migrations.AddIndex(
            model_name='rostermembershipuuid7polyfillsource',
            index=models.Index(fields=['roster_id'], name='rms7_roster_id_idx'),
        ),
        migrations.AddIndex(
            model_name='rostermembershipuuid7polyfillsource',
            index=models.Index(fields=['member_id'], name='rms7_member_id_idx'),
        ),
        migrations.AddIndex(
            model_name='widecustomersource',
            index=models.Index(fields=['region_id'], name='wcs_region_id_idx'),
        ),
        migrations.AddIndex(
            model_name='widecustomeru7source',
            index=models.Index(fields=['region_id'], name='wcs7_region_id_idx'),
        ),
    ]
