# Generated by Django 6.0.7 on 2026-08-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_shared', '0018_rostermembershipsource_rms_roster_id_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nullableuniquetestsource',
            index=models.Index(fields=['badge'], name='nuts_badge_idx'),
        ),
        migrations.AddIndex(
            model_name='softdeleteuniquetestsource',
            index=models.Index(fields=['email'], name='sdus_email_idx'),
        ),
        migrations.AddIndex(
            model_name='softdeleteuniquetestsource',
            index=models.Index(fields=['ssn'], name='sdus_ssn_idx'),
        ),
        migrations.AddIndex(
            model_name='softdeleteuniquetestsource',
            index=models.Index(fields=['first_name', 'last_name'], name='sdus_name_idx'),
        ),
        migrations.AddIndex(
            model_name='uniquetestcompositesource',
            index=models.Index(fields=['first_name', 'last_name'], name='utcs_name_idx'),
        ),
        migrations.AddIndex(
            model_name='uniquetestsource',
            index=models.Index(fields=['ssn'], name='uts_ssn_idx'),
        ),
    ]
