# Generated by Django 6.0.7 on 2026-08-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_shared', '0019_nullableuniquetestsource_nuts_badge_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NullableFkOverlaySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('person_id', models.IntegerField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['person_id'], name='nfos_person_id_idx')],
            },
        ),
    ]
