# Generated by Django 6.0.7 on 2026-08-15 13:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_shared', '0020_nullablefkoverlaysource'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchAddressSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line1', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=2)),
            ],
            options={
                'indexes': [models.Index(fields=['city'], name='bas_city_idx'), models.Index(fields=['postcode'], name='bas_postcode_idx'), models.Index(fields=['country'], name='bas_country_idx')],
            },
        ),
        migrations.CreateModel(
            name='BenchEmailSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['address'], name='bes_address_idx'), models.Index(fields=['domain'], name='bes_domain_idx')],
            },
        ),
        migrations.CreateModel(
            name='BenchPersonAddressSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_id', models.UUIDField()),
                ('address_id', models.UUIDField()),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['person_id'], name='bpas_person_idx'), models.Index(fields=['address_id'], name='bpas_address_idx'), models.Index(fields=['person_id', 'address_id'], name='bpas_pair_idx')],
            },
        ),
        migrations.CreateModel(
            name='BenchPersonEmailSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_id', models.UUIDField()),
                ('email_id', models.UUIDField()),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['person_id'], name='bpes_person_idx'), models.Index(fields=['email_id'], name='bpes_email_idx'), models.Index(fields=['person_id', 'email_id'], name='bpes_pair_idx')],
            },
        ),
        migrations.CreateModel(
            name='BenchPersonPhoneSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_id', models.UUIDField()),
                ('phone_id', models.UUIDField()),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['person_id'], name='bpps_person_idx'), models.Index(fields=['phone_id'], name='bpps_phone_idx'), models.Index(fields=['person_id', 'phone_id'], name='bpps_pair_idx')],
            },
        ),
        migrations.CreateModel(
            name='BenchPersonSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('score', models.IntegerField(null=True)),
                ('born_on', models.DateField(null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['last_name'], name='bps_last_name_idx'), models.Index(fields=['city'], name='bps_city_idx'), models.Index(fields=['status'], name='bps_status_idx'), models.Index(fields=['score'], name='bps_score_idx'), models.Index(fields=['city', '-score'], name='bps_city_score_idx'), models.Index(fields=['last_name', '-score'], name='bps_lname_score_idx')],
            },
        ),
        migrations.CreateModel(
            name='BenchPhoneSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32)),
                ('kind', models.CharField(max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['number'], name='bhs_number_idx'), models.Index(fields=['kind'], name='bhs_kind_idx')],
            },
        ),
    ]
