# Generated by Django 6.0.7 on 2026-08-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_shared', '0021_benchaddresssource_benchemailsource_and_more'),
    ]

    # These tables have to exist before *any* testapp migration runs, not just
    # before the one that introduced them.
    #
    # SyncOverlayView renders the view from the live model, so replaying an old
    # migration emits today's view definition — including a source branch for a
    # source the model only gained now. The migration that first created
    # MetaTest's view therefore selects from testapp_shared_metatestsource, and
    # a fresh database builds testapp before testapp_shared unless told
    # otherwise. Postgres validates references at CREATE VIEW, so it fails
    # there rather than later.
    run_before = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomManagerTestSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='x', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DigitLeadingTableNameTestSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='x', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MetaTestSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonNoteSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RenameFieldTestSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renamed_field', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoftDeletePlainUniqueTestSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('tag', models.CharField(blank=True, default='', max_length=20)),
                ('vendor_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueTestNoSoftDeleteSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VendorThingSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField()),
                ('label', models.CharField(default='x', max_length=100)),
            ],
        ),
    ]
