# Generated by Django 6.0.7 on 2026-08-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    # Same reason as 0022: an overlay view is rendered from live code, so
    # replaying any testapp migration expects today's source tables — indexes
    # included, since the parity check reads them at boot.
    run_before = [
        ('testapp', '0001_initial'),
    ]

    dependencies = [
        ('testapp_shared', '0022_custommanagertestsource_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='metatestsource',
            index=models.Index(fields=['name'], name='metatestsource_name_idx'),
        ),
        migrations.AddIndex(
            model_name='personnotesource',
            index=models.Index(fields=['person_id'], name='personnotesource_person_idx'),
        ),
        migrations.AddIndex(
            model_name='softdeleteplainuniquetestsource',
            index=models.Index(fields=['code'], name='sdputs_code_idx'),
        ),
        migrations.AddIndex(
            model_name='softdeleteplainuniquetestsource',
            index=models.Index(fields=['vendor_id'], name='sdputs_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='uniquetestnosoftdeletesource',
            index=models.Index(fields=['ssn'], name='utnsds_ssn_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorthingsource',
            index=models.Index(fields=['vendor_id'], name='vendorthingsource_vendor_idx'),
        ),
    ]
