# Generated by Django 6.0.7 on 2026-07-24 15:11

import django.db.models.deletion
import django_overlay.fields
import django_overlay.operations
import django_overlay.uuid7
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("testapp_shared", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'address_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddressUuid4',
            fields=[
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'address_uuid4_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddressUuid7Polyfill',
            fields=[
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'address_uuid7polyfill_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'person_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonUuid4',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'person_uuid4_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonUuid7Polyfill',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'person_uuid7polyfill_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'phone_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneUuid4',
            fields=[
                ('number', models.CharField(max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_uuid4_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneUuid7Polyfill',
            fields=[
                ('number', models.CharField(max_length=20)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_uuid7polyfill_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddressBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='AddressUuid4Base',
            fields=[
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'address_uuid4',
            },
        ),
        migrations.CreateModel(
            name='AddressUuid7PolyfillBase',
            fields=[
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'address_uuid7polyfill',
            },
        ),
        migrations.CreateModel(
            name='PersonBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='PersonUuid4Base',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'person_uuid4',
            },
        ),
        migrations.CreateModel(
            name='PersonUuid7PolyfillBase',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'person_uuid7polyfill',
            },
        ),
        migrations.CreateModel(
            name='PhoneBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'phone',
            },
        ),
        migrations.CreateModel(
            name='PhoneTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneUuid4Base',
            fields=[
                ('number', models.CharField(max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_uuid4',
            },
        ),
        migrations.CreateModel(
            name='PhoneUuid7PolyfillBase',
            fields=[
                ('number', models.CharField(max_length=20)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_uuid7polyfill',
            },
        ),
        migrations.CreateModel(
            name='AddressNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('address', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='testapp.address')),
            ],
        ),
        migrations.CreateModel(
            name='AddressNoteUuid4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('address', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='testapp.addressuuid4')),
            ],
        ),
        migrations.CreateModel(
            name='AddressNoteUuid7Polyfill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('address', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='testapp.addressuuid7polyfill')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAddressThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='home', max_length=100)),
                ('address', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.address')),
                ('person', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAddressThroughUuid4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='home', max_length=100)),
                ('address', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.addressuuid4')),
                ('person', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.personuuid4')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAddressThroughUuid7Polyfill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='home', max_length=100)),
                ('address', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.addressuuid7polyfill')),
                ('person', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.personuuid7polyfill')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPhoneThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='mobile', max_length=100)),
                ('person', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.person')),
                ('phone', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.phone')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPhoneThroughUuid4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='mobile', max_length=100)),
                ('person', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.personuuid4')),
                ('phone', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.phoneuuid4')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPhoneThroughUuid7Polyfill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='mobile', max_length=100)),
                ('person', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.personuuid7polyfill')),
                ('phone', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.phoneuuid7polyfill')),
            ],
        ),
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('person', django_overlay.fields.OverlayOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='testapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonProfileUuid4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('person', django_overlay.fields.OverlayOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='testapp.personuuid4')),
            ],
        ),
        migrations.CreateModel(
            name='PersonProfileUuid7Polyfill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('person', django_overlay.fields.OverlayOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='testapp.personuuid7polyfill')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneTagPhoneThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.phone')),
                ('phonetag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.phonetag')),
            ],
        ),
        migrations.AddField(
            model_name='phonetag',
            name='phones',
            field=django_overlay.fields.OverlayManyToManyField(related_name='tags', through='testapp.PhoneTagPhoneThrough', to='testapp.phone'),
        ),
        migrations.CreateModel(
            name='PhoneTagPhoneThroughUuid4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.phoneuuid4')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneTagPhoneThroughUuid7Polyfill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.phoneuuid7polyfill')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneTagUuid4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phones', django_overlay.fields.OverlayManyToManyField(related_name='tags', through='testapp.PhoneTagPhoneThroughUuid4', to='testapp.phoneuuid4')),
            ],
        ),
        migrations.AddField(
            model_name='phonetagphonethroughuuid4',
            name='phonetag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.phonetaguuid4'),
        ),
        migrations.CreateModel(
            name='PhoneTagUuid7Polyfill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phones', django_overlay.fields.OverlayManyToManyField(related_name='tags', through='testapp.PhoneTagPhoneThroughUuid7Polyfill', to='testapp.phoneuuid7polyfill')),
            ],
        ),
        migrations.AddField(
            model_name='phonetagphonethroughuuid7polyfill',
            name='phonetag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.phonetaguuid7polyfill'),
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='Address',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='AddressUuid4',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='AddressUuid7Polyfill',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='Person',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='PersonUuid4',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='PersonUuid7Polyfill',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='Phone',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='PhoneUuid4',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='PhoneUuid7Polyfill',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='AddressNote',
            field_name='address',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='AddressNoteUuid4',
            field_name='address',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='AddressNoteUuid7Polyfill',
            field_name='address',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PersonAddressThrough',
            field_name='address',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PersonAddressThrough',
            field_name='person',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PersonAddressThroughUuid4',
            field_name='address',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PersonAddressThroughUuid4',
            field_name='person',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PersonAddressThroughUuid7Polyfill',
            field_name='address',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PersonAddressThroughUuid7Polyfill',
            field_name='person',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PersonPhoneThrough',
            field_name='person',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PersonPhoneThrough',
            field_name='phone',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PersonPhoneThroughUuid4',
            field_name='person',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PersonPhoneThroughUuid4',
            field_name='phone',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PersonPhoneThroughUuid7Polyfill',
            field_name='person',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PersonPhoneThroughUuid7Polyfill',
            field_name='phone',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PersonProfile',
            field_name='person',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PersonProfileUuid4',
            field_name='person',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PersonProfileUuid7Polyfill',
            field_name='person',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PhoneTagPhoneThrough',
            field_name='phone',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PhoneTagPhoneThroughUuid4',
            field_name='phone',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PhoneTagPhoneThroughUuid7Polyfill',
            field_name='phone',
        ),
    ]
