# Generated by Django 6.0.7 on 2026-07-24 15:15

import django_overlay.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
        ('testapp_shared', '0002_reservedwordsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'reservedword_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservedWordBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'reservedword',
            },
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='ReservedWord',
        ),
    ]
