# Generated by Django 6.0.7 on 2026-07-24 15:23

import django_overlay.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_reservedword_reservedwordbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'meta test',
                'db_table': 'metatest_view',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetaTestBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'metatest',
                'constraints': [models.CheckConstraint(condition=models.Q(('name__gt', '')), name='metatest_name_not_empty')],
            },
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='MetaTest',
        ),
    ]
