# Generated by Django 6.0.7 on 2026-07-24 15:26

import django_overlay.constraints
import django_overlay.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_metatest_metatestbase'),
        ('testapp_shared', '0003_uniquetestsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'uniquetest_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniqueTestBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'uniquetest',
                'constraints': [django_overlay.constraints.OverlayUniqueConstraint(fields=('ssn',), name='uniquetest_ssn_unique')],
            },
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='UniqueTest',
        ),
        django_overlay.operations.AddOverlayUniqueConstraint(
            app_label='testapp',
            model_name='UniqueTest',
            constraint_name='uniquetest_ssn_unique',
        ),
    ]
