# Generated by Django 6.0.7 on 2026-07-24 15:27

import django_overlay.constraints
import django_overlay.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_uniquetest_uniquetestbase'),
        ('testapp_shared', '0004_uniquetestcompositesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueTestComposite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'uniquetestcomposite_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniqueTestCompositeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'uniquetestcomposite',
                'constraints': [django_overlay.constraints.OverlayUniqueConstraint(fields=('first_name', 'last_name'), name='uniquetestcomposite_name_unique')],
            },
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='UniqueTestComposite',
        ),
        django_overlay.operations.AddOverlayUniqueConstraint(
            app_label='testapp',
            model_name='UniqueTestComposite',
            constraint_name='uniquetestcomposite_name_unique',
        ),
    ]
