# Generated by Django 6.0.7 on 2026-07-24 15:42

import django_overlay.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_apply_the_renames'),
        ('testapp_shared', '0005_providerapersonsource_providerbpersonsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchableSourceTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'switchablesourcetest_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwitchableSourceTestBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'switchablesourcetest',
            },
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='SwitchableSourceTest',
        ),
    ]
