# Generated by Django 6.0.7 on 2026-07-24 20:15

import django.db.models.deletion
import django_overlay.constraints
import django_overlay.fields
import django_overlay.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_switchablesourcetest_switchablesourcetestbase'),
        ('testapp_shared', '0007_uniquetestsource_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredSourceTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'filteredsourcetest_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniqueTestNoSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'uniquetestnosource_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilteredSourceTestBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'filteredsourcetest',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MetaTestNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NullableFkTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UniqueTestNoSourceBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'uniquetestnosource',
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='addressbase',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='addressuuid4base',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='addressuuid7polyfillbase',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='metatestbase',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='personbase',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='personuuid4base',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='personuuid7polyfillbase',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='phonebase',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='phoneuuid4base',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='phoneuuid7polyfillbase',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='renamefieldtestbase',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='reservedwordbase',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='switchablesourcetestbase',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='uniquetestbase',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='uniquetestcompositebase',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelTableComment(
            name='metatestbase',
            table_comment='Meta forwarding test fixture',
        ),
        migrations.AddField(
            model_name='uniquetestbase',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='metatestbase',
            unique_together={('name',)},
        ),
        migrations.AddIndex(
            model_name='metatestbase',
            index=models.Index(fields=['name'], name='metatest_name_idx'),
        ),
        migrations.AddField(
            model_name='metatestnote',
            name='meta_test',
            field=django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='testapp.metatest'),
        ),
        migrations.AddField(
            model_name='nullablefktest',
            name='address',
            field=django_overlay.fields.OverlayForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nullable_fk_tests', to='testapp.address'),
        ),
        migrations.AddConstraint(
            model_name='uniquetestnosourcebase',
            constraint=django_overlay.constraints.OverlayUniqueConstraint(fields=('ssn',), name='uniquetestnosource_ssn_unique'),
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='FilteredSourceTest',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='UniqueTestNoSource',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='UniqueTest',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='metatestnote',
            field_name='meta_test',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='nullablefktest',
            field_name='address',
        ),
        django_overlay.operations.AddOverlayUniqueConstraint(
            app_label='testapp',
            model_name='UniqueTestNoSource',
            constraint_name='uniquetestnosource_ssn_unique',
        ),
    ]
