# Generated by Django 6.0.7 on 2026-07-24 23:47

import django.db.models.deletion
import django_overlay.fields
import django_overlay.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_remove_removableuniquetest_ssn_unique'),
        ('testapp_shared', '0009_softdeletetestsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftDeleteTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'softdeletetest_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoftDeleteTestNoSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='x', max_length=100)),
            ],
            options={
                'db_table': 'softdeletetestnosource_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoftDeleteTestBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'softdeletetest',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SoftDeleteTestNoSourceBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='x', max_length=100)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'softdeletetestnosource',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SoftDeleteTestNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('target', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='testapp.softdeletetest')),
            ],
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='SoftDeleteTest',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='SoftDeleteTestNoSource',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='SoftDeleteTestNote',
            field_name='target',
        ),
    ]
