# Generated by Django 6.0.7 on 2026-07-25 02:05

import django_overlay.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_softdeletetest_softdeletetestnosource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitLeadingTableNameTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='x', max_length=100)),
            ],
            options={
                'db_table': '123digitleadingtablenametest_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DigitLeadingTableNameTestBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='x', max_length=100)),
            ],
            options={
                'db_table': '123digitleadingtablenametest',
                'default_permissions': (),
            },
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='DigitLeadingTableNameTest',
        ),
    ]
