# Generated by Django 6.0.7 on 2026-08-13 14:02

import django.db.models.deletion
import django_overlay.fields
import django_overlay.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_digitleadingtablenametest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'personnote_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VendorThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='x', max_length=100)),
            ],
            options={
                'db_table': 'vendorthing_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonNoteBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('person', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.person')),
            ],
            options={
                'db_table': 'personnote',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='VendorThingBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='x', max_length=100)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.vendor')),
            ],
            options={
                'db_table': 'vendorthing',
                'default_permissions': (),
            },
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='PersonNote',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='PersonNoteBase',
            field_name='person',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='VendorThing',
        ),
    ]
