# Generated by Django 6.0.7 on 2026-08-13 14:09

import django_overlay.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_personnote_vendorthing_vendor_personnotebase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomManagerTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='x', max_length=100)),
            ],
            options={
                'db_table': 'custommanagertest_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomManagerTestBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='x', max_length=100)),
            ],
            options={
                'db_table': 'custommanagertest',
                'default_permissions': (),
            },
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='CustomManagerTest',
        ),
    ]
