# Generated by Django 6.0.7 on 2026-08-13 19:45

import django.db.models.deletion
import django_overlay.constraints
import django_overlay.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_custommanagertest_custommanagertestbase'),
        ('testapp_shared', '0010_softdeleteuniquetestsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftDeletePlainUniqueTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('tag', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'db_table': 'softdeleteplainuniquetest_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoftDeleteUniqueTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'softdeleteuniquetest_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoftDeletePlainUniqueTestBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('tag', models.CharField(blank=True, default='', max_length=20)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'softdeleteplainuniquetest',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SoftDeleteUniqueTestBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'softdeleteuniquetest',
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='metatestbase',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='metatestbase',
            constraint=django_overlay.constraints.OverlayUniqueConstraint(fields=('name',), name='metatest_name_unique'),
        ),
        migrations.AddField(
            model_name='softdeleteplainuniquetestbase',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.vendor'),
        ),
        migrations.AddConstraint(
            model_name='softdeleteuniquetestbase',
            constraint=django_overlay.constraints.OverlayUniqueConstraint(fields=('ssn',), name='softdeleteuniquetest_ssn_unique', soft_delete=True),
        ),
        migrations.AddConstraint(
            model_name='softdeleteuniquetestbase',
            constraint=django_overlay.constraints.OverlayUniqueConstraint(fields=('first_name', 'last_name'), name='softdeleteuniquetest_first_name_last_name_uniq', soft_delete=True),
        ),
        migrations.AddConstraint(
            model_name='softdeleteuniquetestbase',
            constraint=django_overlay.constraints.OverlayUniqueConstraint(fields=('email',), name='softdeleteuniquetest_email_uniq', soft_delete=True),
        ),
        migrations.AddConstraint(
            model_name='softdeleteplainuniquetestbase',
            constraint=django_overlay.constraints.OverlayUniqueConstraint(fields=('vendor',), name='softdeleteplainuniquetest_vendor_uniq', soft_delete=True),
        ),
        migrations.AddConstraint(
            model_name='softdeleteplainuniquetestbase',
            constraint=django_overlay.constraints.OverlayUniqueConstraint(fields=('code',), name='softdeleteplainuniquetest_code', soft_delete=True),
        ),
        migrations.AddConstraint(
            model_name='softdeleteplainuniquetestbase',
            constraint=models.CheckConstraint(condition=models.Q(('code__gt', '')), name='softdeleteplainuniquetest_code_not_empty'),
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='SoftDeletePlainUniqueTest',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='SoftDeleteUniqueTest',
        ),
        django_overlay.operations.AddOverlayUniqueConstraint(
            app_label='testapp',
            model_name='MetaTest',
            constraint_name='metatest_name_unique',
        ),
        django_overlay.operations.AddOverlayUniqueConstraint(
            app_label='testapp',
            model_name='SoftDeleteUniqueTest',
            constraint_name='softdeleteuniquetest_ssn_unique',
        ),
        django_overlay.operations.AddOverlayUniqueConstraint(
            app_label='testapp',
            model_name='SoftDeleteUniqueTest',
            constraint_name='softdeleteuniquetest_first_name_last_name_uniq',
        ),
        django_overlay.operations.AddOverlayUniqueConstraint(
            app_label='testapp',
            model_name='SoftDeleteUniqueTest',
            constraint_name='softdeleteuniquetest_email_uniq',
        ),
        django_overlay.operations.AddOverlayUniqueConstraint(
            app_label='testapp',
            model_name='SoftDeletePlainUniqueTest',
            constraint_name='softdeleteplainuniquetest_vendor_uniq',
        ),
        django_overlay.operations.AddOverlayUniqueConstraint(
            app_label='testapp',
            model_name='SoftDeletePlainUniqueTest',
            constraint_name='softdeleteplainuniquetest_code',
        ),
    ]
