# Generated by Django 6.0.7 on 2026-08-14 12:05

import django_overlay.constraints
import django_overlay.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_remove_metatestbase_metatest_name_unique_and_more'),
        # The view selects from the source table, and makemigrations can't see
        # that -- get_source() names it as a string, not a relation.
        ('testapp_shared', '0011_nullableuniquetestsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='NullableUniqueTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(max_length=20, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'nullableuniquetest_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NullableUniqueTestBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(max_length=20, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'nullableuniquetest',
                'default_permissions': (),
                'constraints': [django_overlay.constraints.OverlayUniqueConstraint(fields=('badge',), name='nullableuniquetest_badge_uniq', soft_delete=True)],
            },
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='NullableUniqueTest',
        ),
        django_overlay.operations.AddOverlayUniqueConstraint(
            app_label='testapp',
            model_name='NullableUniqueTest',
            constraint_name='nullableuniquetest_badge_uniq',
        ),
    ]
