# Generated by Django 6.0.7 on 2026-08-14 15:21

import django.db.models.deletion
import django_overlay.fields
import django_overlay.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0020_nullableuniquetest_nullableuniquetestbase'),
        # Hand-added. The views created below select from the Wide*Source
        # tables, but get_source() names them as a string rather than a
        # relation, so makemigrations cannot see the dependency.
        ('testapp_shared', '0012_widecustomersource_wideorderlinesource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WideCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('age', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('score', models.IntegerField(null=True)),
                ('registered_on', models.DateField(null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'widecustomer_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WideOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=20)),
                ('total_cents', models.IntegerField()),
                ('placed_on', models.DateField(null=True)),
                ('channel', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=3)),
                ('comment', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'wideorder_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WideOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price_cents', models.IntegerField()),
                ('discount_cents', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'wideorderline_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WideProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=60)),
                ('price_cents', models.IntegerField()),
                ('weight_grams', models.IntegerField(null=True)),
                ('supplier', models.CharField(max_length=100)),
                ('discontinued', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'wideproduct_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WideRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='WideProductBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=60)),
                ('price_cents', models.IntegerField()),
                ('weight_grams', models.IntegerField(null=True)),
                ('supplier', models.CharField(max_length=100)),
                ('discontinued', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'wideproduct',
                'default_permissions': (),
                'indexes': [models.Index(fields=['category'], name='wideproduct_category_idx'), models.Index(fields=['sku'], name='wideproduct_sku_idx')],
            },
        ),
        migrations.CreateModel(
            name='WideCustomerNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('customer', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notes', to='testapp.widecustomer')),
            ],
            options={
                'indexes': [models.Index(fields=['customer'], name='widecustomernote_customer_idx')],
            },
        ),
        migrations.CreateModel(
            name='WideOrderBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=20)),
                ('total_cents', models.IntegerField()),
                ('placed_on', models.DateField(null=True)),
                ('channel', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=3)),
                ('comment', models.TextField(blank=True, default='')),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
                ('customer', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.widecustomer')),
            ],
            options={
                'db_table': 'wideorder',
                'default_permissions': (),
                'indexes': [models.Index(fields=['status'], name='wideorder_status_idx'), models.Index(fields=['channel'], name='wideorder_channel_idx'), models.Index(fields=['customer'], name='wideorder_customer_idx')],
            },
        ),
        migrations.CreateModel(
            name='WideOrderLineBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price_cents', models.IntegerField()),
                ('discount_cents', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
                ('order', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.wideorder')),
                ('product', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.wideproduct')),
            ],
            options={
                'db_table': 'wideorderline',
                'default_permissions': (),
                'indexes': [models.Index(fields=['order'], name='wideorderline_order_idx'), models.Index(fields=['product'], name='wideorderline_product_idx')],
            },
        ),
        migrations.CreateModel(
            name='WideCustomerBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('age', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('score', models.IntegerField(null=True)),
                ('registered_on', models.DateField(null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='testapp.wideregion')),
            ],
            options={
                'db_table': 'widecustomer',
                'default_permissions': (),
                'indexes': [models.Index(fields=['last_name'], name='widecustomer_last_name_idx'), models.Index(fields=['city'], name='widecustomer_city_idx'), models.Index(fields=['status'], name='widecustomer_status_idx'), models.Index(fields=['score'], name='widecustomer_score_idx'), models.Index(fields=['age'], name='widecustomer_age_idx')],
            },
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='WideProduct',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='WideCustomerNote',
            field_name='customer',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='WideOrder',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='WideOrderBase',
            field_name='customer',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='WideOrderLine',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='WideOrderLineBase',
            field_name='order',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='WideOrderLineBase',
            field_name='product',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='WideCustomer',
        ),
    ]
