# Generated by Django 6.0.7 on 2026-08-14 21:01

import django_overlay.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_widecustomer_wideorder_wideorderline_wideproduct_and_more'),
        # Hand-added. The view created below selects from
        # HardDeleteCountTestSource, but get_source() names it as a string
        # rather than a relation, so makemigrations cannot see the dependency.
        ('testapp_shared', '0013_harddeletecounttestsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardDeleteCountTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'harddeletecounttest_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HardDeleteCountTestBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'harddeletecounttest',
                'default_permissions': (),
            },
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='HardDeleteCountTest',
        ),
    ]
