# Generated by Django 6.0.7 on 2026-08-14 21:24

import django.db.models.deletion
import django_overlay.fields
import django_overlay.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0022_harddeletecounttest_harddeletecounttestbase'),
        # Hand-added. The views created below select from the *Source tables,
        # but get_source() names them as strings rather than relations, so
        # makemigrations cannot see the dependency.
        ('testapp_shared', '0014_auditentrysource_membersource_rostermembershipsource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auditentry_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'member_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'roster_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RosterMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='member', max_length=50)),
            ],
            options={
                'db_table': 'rostermembership_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditEntryBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auditentry',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MemberBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'member',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RosterBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'roster',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RosterMembershipBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='member', max_length=50)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
                ('member', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.member')),
                ('roster', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.roster')),
            ],
            options={
                'db_table': 'rostermembership',
                'default_permissions': (),
            },
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='AuditEntry',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='Member',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='Roster',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='RosterMembership',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='RosterMembershipBase',
            field_name='member',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='RosterMembershipBase',
            field_name='roster',
        ),
    ]
