# Generated by Django 6.0.7 on 2026-08-14 21:46

import django.db.models.deletion
import django_overlay.fields
import django_overlay.operations
import django_overlay.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0023_auditentry_member_roster_rostermembership_and_more'),
        # Hand-added. The views created below select from the *Source tables,
        # but get_source() names them as strings rather than relations, so
        # makemigrations cannot see the dependency.
        ('testapp_shared', '0015_memberuuid7polyfillsource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberUuid7Polyfill',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'member_uuid7polyfill_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RosterMembershipUuid7Polyfill',
            fields=[
                ('role', models.CharField(default='member', max_length=50)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rostermembership_uuid7polyfill_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RosterUuid7Polyfill',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'roster_uuid7polyfill_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberUuid7PolyfillBase',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'member_uuid7polyfill',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RosterUuid7PolyfillBase',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'roster_uuid7polyfill',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RosterMembershipUuid7PolyfillBase',
            fields=[
                ('role', models.CharField(default='member', max_length=50)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
                ('member', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.memberuuid7polyfill')),
                ('roster', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.rosteruuid7polyfill')),
            ],
            options={
                'db_table': 'rostermembership_uuid7polyfill',
                'default_permissions': (),
            },
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='MemberUuid7Polyfill',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='RosterUuid7Polyfill',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='RosterMembershipUuid7Polyfill',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='RosterMembershipUuid7PolyfillBase',
            field_name='member',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='RosterMembershipUuid7PolyfillBase',
            field_name='roster',
        ),
    ]
