# Generated by Django 6.0.7 on 2026-08-14 22:02

import django.db.models.deletion
import django_overlay.fields
import django_overlay.operations
import django_overlay.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0024_memberuuid7polyfill_rostermembershipuuid7polyfill_and_more'),
        # Hand-added. The views created below select from the *U7Source
        # tables, but get_source() names them as strings rather than
        # relations, so makemigrations cannot see the dependency.
        ('testapp_shared', '0016_widecustomeru7source_wideorderlineu7source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WideCustomerU7',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('age', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('score', models.IntegerField(null=True)),
                ('registered_on', models.DateField(null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'widecustomer_u7_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WideOrderLineU7',
            fields=[
                ('quantity', models.IntegerField()),
                ('unit_price_cents', models.IntegerField()),
                ('discount_cents', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wideorderline_u7_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WideOrderU7',
            fields=[
                ('reference', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=20)),
                ('total_cents', models.IntegerField()),
                ('placed_on', models.DateField(null=True)),
                ('channel', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=3)),
                ('comment', models.TextField(blank=True, default='')),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wideorder_u7_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WideProductU7',
            fields=[
                ('sku', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=60)),
                ('price_cents', models.IntegerField()),
                ('weight_grams', models.IntegerField(null=True)),
                ('supplier', models.CharField(max_length=100)),
                ('discontinued', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wideproduct_u7_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WideProductU7Base',
            fields=[
                ('sku', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=60)),
                ('price_cents', models.IntegerField()),
                ('weight_grams', models.IntegerField(null=True)),
                ('supplier', models.CharField(max_length=100)),
                ('discontinued', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'wideproduct_u7',
                'default_permissions': (),
                'indexes': [models.Index(fields=['category'], name='wideproductu7_category_idx'), models.Index(fields=['sku'], name='wideproductu7_sku_idx')],
            },
        ),
        migrations.CreateModel(
            name='WideCustomerNoteU7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('customer', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notes', to='testapp.widecustomeru7')),
            ],
            options={
                'indexes': [models.Index(fields=['customer'], name='widecustomernoteu7_customer_idx')],
            },
        ),
        migrations.CreateModel(
            name='WideCustomerU7Base',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('age', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('score', models.IntegerField(null=True)),
                ('registered_on', models.DateField(null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='testapp.wideregion')),
            ],
            options={
                'db_table': 'widecustomer_u7',
                'default_permissions': (),
                'indexes': [models.Index(fields=['last_name'], name='widecustomeru7_last_name_idx'), models.Index(fields=['city'], name='widecustomeru7_city_idx'), models.Index(fields=['status'], name='widecustomeru7_status_idx'), models.Index(fields=['score'], name='widecustomeru7_score_idx'), models.Index(fields=['age'], name='widecustomeru7_age_idx')],
            },
        ),
        migrations.CreateModel(
            name='WideOrderLineU7Base',
            fields=[
                ('quantity', models.IntegerField()),
                ('unit_price_cents', models.IntegerField()),
                ('discount_cents', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
                ('order', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.wideorderu7')),
                ('product', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.wideproductu7')),
            ],
            options={
                'db_table': 'wideorderline_u7',
                'default_permissions': (),
                'indexes': [models.Index(fields=['order'], name='wideorderlineu7_order_idx'), models.Index(fields=['product'], name='wideorderlineu7_product_idx')],
            },
        ),
        migrations.CreateModel(
            name='WideOrderU7Base',
            fields=[
                ('reference', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=20)),
                ('total_cents', models.IntegerField()),
                ('placed_on', models.DateField(null=True)),
                ('channel', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=3)),
                ('comment', models.TextField(blank=True, default='')),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
                ('customer', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.widecustomeru7')),
            ],
            options={
                'db_table': 'wideorder_u7',
                'default_permissions': (),
                'indexes': [models.Index(fields=['status'], name='wideorderu7_status_idx'), models.Index(fields=['channel'], name='wideorderu7_channel_idx'), models.Index(fields=['customer'], name='wideorderu7_customer_idx')],
            },
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='WideProductU7',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='WideCustomerNoteU7',
            field_name='customer',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='WideCustomerU7',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='WideOrderLineU7',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='WideOrderLineU7Base',
            field_name='order',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='WideOrderLineU7Base',
            field_name='product',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='WideOrderU7',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='WideOrderU7Base',
            field_name='customer',
        ),
    ]
