# Generated by Django 6.0.7 on 2026-08-15 10:26

import django.db.models.deletion
import django_overlay.fields
import django_overlay.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0025_widecustomeru7_wideorderlineu7_wideorderu7_and_more'),
        # Hand-added. The view created below selects from
        # NullableFkOverlaySource, but get_source() names it as a string
        # rather than a relation, so makemigrations cannot see it.
        ('testapp_shared', '0020_nullablefkoverlaysource'),
    ]

    operations = [
        migrations.CreateModel(
            name='NullableFkOverlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nullablefkoverlay_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NullableFkOverlayBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
                ('person', django_overlay.fields.OverlayForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='testapp.person')),
            ],
            options={
                'db_table': 'nullablefkoverlay',
                'default_permissions': (),
            },
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='NullableFkOverlay',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='NullableFkOverlayBase',
            field_name='person',
        ),
    ]
