# Generated by Django 6.0.7 on 2026-08-15 13:12

import django.db.models.deletion
import django_overlay.fields
import django_overlay.operations
import django_overlay.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0026_nullablefkoverlay_nullablefkoverlaybase'),
        # Hand-added, same reason as 0025: the views created below select from
        # the Bench*Source tables, but get_source() names them as strings
        # rather than relations, so makemigrations cannot see the dependency.
        ('testapp_shared', '0021_benchaddresssource_benchemailsource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchAddress',
            fields=[
                ('line1', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=2)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bench_address_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BenchEmail',
            fields=[
                ('address', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=20)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bench_email_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BenchPerson',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('score', models.IntegerField(null=True)),
                ('born_on', models.DateField(null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bench_person_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BenchPersonAddress',
            fields=[
                ('role', models.CharField(default='home', max_length=20)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bench_person_address_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BenchPersonEmail',
            fields=[
                ('role', models.CharField(default='primary', max_length=20)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bench_person_email_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BenchPersonPhone',
            fields=[
                ('role', models.CharField(default='mobile', max_length=20)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bench_person_phone_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BenchPhone',
            fields=[
                ('number', models.CharField(max_length=32)),
                ('kind', models.CharField(max_length=20)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bench_phone_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BenchAddressBase',
            fields=[
                ('line1', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=2)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'bench_address',
                'default_permissions': (),
                'indexes': [models.Index(fields=['city'], name='ba_city_idx'), models.Index(fields=['postcode'], name='ba_postcode_idx'), models.Index(fields=['country'], name='ba_country_idx')],
            },
        ),
        migrations.CreateModel(
            name='BenchEmailBase',
            fields=[
                ('address', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=20)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'bench_email',
                'default_permissions': (),
                'indexes': [models.Index(fields=['address'], name='be_address_idx'), models.Index(fields=['domain'], name='be_domain_idx')],
            },
        ),
        migrations.CreateModel(
            name='BenchPersonBase',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('score', models.IntegerField(null=True)),
                ('born_on', models.DateField(null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'bench_person',
                'default_permissions': (),
                'indexes': [models.Index(fields=['last_name'], name='bp_last_name_idx'), models.Index(fields=['city'], name='bp_city_idx'), models.Index(fields=['status'], name='bp_status_idx'), models.Index(fields=['score'], name='bp_score_idx'), models.Index(fields=['city', '-score'], name='bp_city_score_idx'), models.Index(fields=['last_name', '-score'], name='bp_lname_score_idx')],
            },
        ),
        migrations.CreateModel(
            name='BenchPhoneBase',
            fields=[
                ('number', models.CharField(max_length=32)),
                ('kind', models.CharField(max_length=20)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('_overlay_deleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'bench_phone',
                'default_permissions': (),
                'indexes': [models.Index(fields=['number'], name='bh_number_idx'), models.Index(fields=['kind'], name='bh_kind_idx')],
            },
        ),
        migrations.CreateModel(
            name='BenchPersonAddressBase',
            fields=[
                ('role', models.CharField(default='home', max_length=20)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('address', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.benchaddress')),
                ('person', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.benchperson')),
            ],
            options={
                'db_table': 'bench_person_address',
                'default_permissions': (),
                'indexes': [models.Index(fields=['person'], name='bpa_person_idx'), models.Index(fields=['address'], name='bpa_address_idx'), models.Index(fields=['person', 'address'], name='bpa_pair_idx')],
            },
        ),
        migrations.CreateModel(
            name='BenchPersonEmailBase',
            fields=[
                ('role', models.CharField(default='primary', max_length=20)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.benchemail')),
                ('person', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.benchperson')),
            ],
            options={
                'db_table': 'bench_person_email',
                'default_permissions': (),
                'indexes': [models.Index(fields=['person'], name='bpe_person_idx'), models.Index(fields=['email'], name='bpe_email_idx'), models.Index(fields=['person', 'email'], name='bpe_pair_idx')],
            },
        ),
        migrations.CreateModel(
            name='BenchPersonPhoneBase',
            fields=[
                ('role', models.CharField(default='mobile', max_length=20)),
                ('id', models.UUIDField(default=django_overlay.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('person', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.benchperson')),
                ('phone', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testapp.benchphone')),
            ],
            options={
                'db_table': 'bench_person_phone',
                'default_permissions': (),
                'indexes': [models.Index(fields=['person'], name='bpp_person_idx'), models.Index(fields=['phone'], name='bpp_phone_idx'), models.Index(fields=['person', 'phone'], name='bpp_pair_idx')],
            },
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='BenchAddress',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='BenchEmail',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='BenchPerson',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='BenchPhone',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='BenchPersonAddress',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='BenchPersonAddressBase',
            field_name='address',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='BenchPersonAddressBase',
            field_name='person',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='BenchPersonEmail',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='BenchPersonEmailBase',
            field_name='email',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='BenchPersonEmailBase',
            field_name='person',
        ),
        django_overlay.operations.SyncOverlayView(
            app_label='testapp',
            model_name='BenchPersonPhone',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='BenchPersonPhoneBase',
            field_name='person',
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='BenchPersonPhoneBase',
            field_name='phone',
        ),
    ]
