# Generated by Django 6.0.7 on 2026-08-15 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0027_benchaddress_benchemail_benchperson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlainPerson',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('score', models.IntegerField(null=True)),
                ('born_on', models.DateField(null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'plain_person',
            },
        ),
        migrations.CreateModel(
            name='PlainAddress',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('line1', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'plain_address',
                'indexes': [models.Index(fields=['city'], name='pa_city_idx'), models.Index(fields=['postcode'], name='pa_postcode_idx'), models.Index(fields=['country'], name='pa_country_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlainEmail',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'plain_email',
                'indexes': [models.Index(fields=['address'], name='pe_address_idx'), models.Index(fields=['domain'], name='pe_domain_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlainPersonAddress',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='home', max_length=20)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.plainaddress')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.plainperson')),
            ],
            options={
                'db_table': 'plain_person_address',
            },
        ),
        migrations.AddField(
            model_name='plainperson',
            name='addresses',
            field=models.ManyToManyField(related_name='people', through='testapp.PlainPersonAddress', to='testapp.plainaddress'),
        ),
        migrations.CreateModel(
            name='PlainPersonEmail',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='primary', max_length=20)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.plainemail')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.plainperson')),
            ],
            options={
                'db_table': 'plain_person_email',
            },
        ),
        migrations.AddField(
            model_name='plainperson',
            name='emails',
            field=models.ManyToManyField(related_name='people', through='testapp.PlainPersonEmail', to='testapp.plainemail'),
        ),
        migrations.CreateModel(
            name='PlainPhone',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32)),
                ('kind', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'plain_phone',
                'indexes': [models.Index(fields=['number'], name='ph_number_idx'), models.Index(fields=['kind'], name='ph_kind_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlainPersonPhone',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='mobile', max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.plainperson')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.plainphone')),
            ],
            options={
                'db_table': 'plain_person_phone',
            },
        ),
        migrations.AddField(
            model_name='plainperson',
            name='phones',
            field=models.ManyToManyField(related_name='people', through='testapp.PlainPersonPhone', to='testapp.plainphone'),
        ),
        migrations.AddIndex(
            model_name='plainperson',
            index=models.Index(fields=['last_name'], name='pp_last_name_idx'),
        ),
        migrations.AddIndex(
            model_name='plainperson',
            index=models.Index(fields=['city'], name='pp_city_idx'),
        ),
        migrations.AddIndex(
            model_name='plainperson',
            index=models.Index(fields=['status'], name='pp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='plainperson',
            index=models.Index(fields=['score'], name='pp_score_idx'),
        ),
        migrations.AddIndex(
            model_name='plainperson',
            index=models.Index(fields=['city', '-score'], name='pp_city_score_idx'),
        ),
        migrations.AddIndex(
            model_name='plainperson',
            index=models.Index(fields=['last_name', '-score'], name='pp_lname_score_idx'),
        ),
    ]
