# Generated by Django 6.0.7 on 2026-08-16 20:19

import django.db.models.deletion
import django_overlay.fields
import django_overlay.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0028_plainperson_plainaddress_plainemail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'bench_label',
                'indexes': [models.Index(fields=['kind'], name='bl_kind_idx'), models.Index(fields=['name'], name='bl_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlainPersonLabel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plain_links', to='testapp.benchlabel')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_links', to='testapp.plainperson')),
            ],
            options={
                'db_table': 'plain_person_label',
            },
        ),
        migrations.AddField(
            model_name='plainperson',
            name='labels',
            field=models.ManyToManyField(related_name='plain_people', through='testapp.PlainPersonLabel', to='testapp.benchlabel'),
        ),
        migrations.CreateModel(
            name='BenchPersonLabel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bench_links', to='testapp.benchlabel')),
                ('person', django_overlay.fields.OverlayForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_links', to='testapp.benchperson')),
            ],
            options={
                'db_table': 'bench_person_label',
                'indexes': [models.Index(fields=['person'], name='bpl_person_idx'), models.Index(fields=['label'], name='bpl_label_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='plainpersonlabel',
            index=models.Index(fields=['person'], name='ppl_person_idx'),
        ),
        migrations.AddIndex(
            model_name='plainpersonlabel',
            index=models.Index(fields=['label'], name='ppl_label_idx'),
        ),
        django_overlay.operations.AddOverlayConstraint(
            app_label='testapp',
            model_name='BenchPersonLabel',
            field_name='person',
        ),
    ]
