# Generated by Django 6.0.7 on 2026-08-23 01:30

import django_overlay.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0029_benchlabel_plainpersonlabel_plainperson_labels_and_more'),
    ]

    operations = [
        django_overlay.operations.DropOverlayView(
            app_label='testapp',
            model_name='SoftDeleteTestNoSourceBase',
        ),
        migrations.DeleteModel(
            name='SoftDeleteTestNoSourceBase',
        ),
        django_overlay.operations.DropOverlayView(
            app_label='testapp',
            model_name='SoftDeleteTestNoSource',
        ),
        migrations.DeleteModel(
            name='SoftDeleteTestNoSource',
        ),
    ]
